### ISSUE TITLE
CRUD operations for Admin interface

### ISSUE THREAD

**Issue by igrigorov** [igrigorov/spring-react-i18n-admin#1]
Create the following endpoints:

- [x] GET /l10n - returns all localization entries in format `{id, locale, lic, value, active}`
- [x] POST /l10n/entry - creates a new entry. Input in format `{locale, lic, value}`
- [x] PUT /l10n/entry/{id} - replaces the entry with `id`. Input in format `{id, locale, lic, value, active}`
  - Update ModifiedOn when updating to current timestamp
- [x] Integration Tests for all the above

**Comment by lambrospap** [comment]
PUT operation was changed in order to be updated with a given **lic** as discussed
